### ISSUE TITLE
HAVING clause is ignored by PrivateReader

### ISSUE THREAD

**Issue by gregaw** [opendp/smartnoise-sdk#287]
Given table `A: (id int, product text, quantity int)`, when you run the following query with a PrivateReader:

```
select product, SUM(quantity) as sm
from A 
group by product
having IDONTEXIST > 1
```
then it returns results as if ignoring the incorrect HAVING statement.

When the same sql runs via a PostgresReader directly, then the appropriate exception is thrown:
`psycopg2.errors.UndefinedColumn: column "idontexist" does not exist`

**Comment by eedeleon** [comment]
@joshua-oss  looks like our rewriter might be dropping having statements rather than failing early or rewriting them properly.

Thanks for letting us know @gregaw , apologies for the delayed response, we will look into this and report back on what can be done within a week

**Comment by joshua-oss** [comment]
Oh, right, we can either fail early and tell people to manually filter the aggregates that are returned, or else just go ahead and implement it.  Because the HAVING clause needs to be applied in post-processing, after the differentially private aggregates are computed, it's not difficult.  The main work is in the validator.

**Comment by eedeleon** [comment]
We have checked in HAVING support. We will close this issue when it reaches pypi

**Comment by gregaw** [comment]
thanks @eedeleon. Appreciated 👍

**Comment by joshua-oss** [comment]
In PyPi
