### ISSUE TITLE
Does the PATECTGAN Conditional Generator leak the privacy?

### ISSUE THREAD

**Issue by Tecnarca** [opendp/smartnoise-sdk#301]
I'm wondering if the PATECTGAN Conditional Generator of the PATECTGAN leaks the privacy of the categorical attributes.
Even without the cross entropy loss of the generator, we are still forcing the Generator of the model to learn using the frequencies of the categorical attributes. This will ultimately result in the generator learning the exact frequencies without any noise applied to them. Is this simply not accounted for (since the DP Guarantee is for row-level privacy) or am I misinterpreting something?

**Comment by eedeleon** [comment]
We had this same issue come up during a review recently. We are looking into it with the broader research team to see if our original assumptions were incorrect.

**Comment by joshua-oss** [comment]
The frequencies for the DataSampler are taken directly from the category frequencies in the data, so the `DataSampler` will sample rows uniformly.  If you create a histogram of category frequencies and convert it to a probability distribution, then sample with (e.g.) np.choose, the resulting sampled data will have the same distribution as if the source rows were sampled uniformly.

The purpose of `DataSampler` is not to oversample any categories, but instead to ensure that rows are sampled uniformly in the order necessary to match the generated masks.  Therefore, we don't believe that this causes a privacy issue.  Tests confirm that the sampler does not result in neighboring databases being distinguishable.  However, we have updated the `DataSampler` to spend some of the epsilon budget on estimating the frequencies privately.  We don't think this is strictly necessary, but it doesn't seem to harm utility.

Note that the above does not apply when `log_frequency=True`.  When the log of frequencies is taken, rare categories will be sampled more than would be expected in uniform sampling, and frequent categories sampled less.  This problem is not solved by using noisy frequencies, so we now set this value to `False` and give a warning if the caller overrides.

PR is here, released in v0.2.4: https://github.com/opendp/smartnoise-sdk/pull/426
