### ISSUE TITLE
TAU calculation

### ISSUE THREAD

**Issue by giulianopietoso-apheris** [opendp/smartnoise-sdk#309]
Looking at this code snippet:

https://github.com/opendifferentialprivacy/smartnoise-sdk/blob/master/sdk/opendp/smartnoise/sql/private_reader.py#L172
https://github.com/opendifferentialprivacy/smartnoise-sdk/blob/master/sdk/opendp/smartnoise/sql/private_reader.py#L173

I struggle to understand what this formula does regarding privacy, could someone explain or point to a paper where this was introduced?

Thank you.

**Comment by joshua-oss** [comment]
This is used to prevent disclosure of the existence of rare dimensions.  For example, if someone does a query such as `SELECT LAST_NAME, COUNT(*)` from a database, adding differentially private noise scaled for epsilon = 0.01, this would provide strong privacy assurances that the counts would not disclose the presence of any individual.  However, the mere existence of a rare surname in the list of dimensions (even if the count is negative), would reveal that this person was in the database.

This attack, and a solution, was first discussed by Korolova: http://theory.stanford.edu/~korolova/Releasing_search_queries_and_clicks_privately_WWW2009.pdf

The threshold for the original Korolova method was derived for Laplace counts.  We use a threshold for Gaussian, since we are using Gaussian for our counts.

We have published on two other techniques for protecting rare dimensions, which sometimes give better yield, depending on data characteristics:
https://arxiv.org/pdf/2002.09745.pdf

We have posted code here for the "Policy Laplace", which can be enabled by setting `use_dpsu` in the metadata.

Also note that our default behavior is to drop rare dimensions, because we want to err on the side of privacy.  There may be cases where you don't want this behavior.  For example, if you are grouping by US ZIP codes, and you know that you will always include possible ZIP codes (returning zero for all dimensions that have no entires, e.g. with an OUTER JOIN).  If you want this behavior, you can set `censor_dims` to false in the metadata.

Some more on the metadata is here:
https://github.com/opendifferentialprivacy/smartnoise-sdk/blob/master/sdk/Metadata.md

There are also a few more papers describing some design of the SQL layer here:
https://github.com/opendifferentialprivacy/smartnoise-sdk/tree/master/papers

We will be adding more soon, especially as we will need to think through user contribution in the case of JOINs, especially in some of the cases highlighted in the answer to your previous question.
