### ISSUE TITLE
update whitenoise module references in code (from older examples/samples)

### ISSUE THREAD

**Issue by raprasad** [opendp/smartnoise-sdk#342]
May need some re-testing with updated modules:

![image](https://user-images.githubusercontent.com/1036060/111639664-d5cf9d80-87d1-11eb-940c-e78e2b6dd81f.png)

**Comment by joshua-oss** [comment]
Thanks for flagging this.  I believe we can delete `test_core` and `dp_core` since these were intended to test that core library was working side-by-side.  Since the SDK now takes a dependency on core in `private_reader`, the core library is tested in most code paths in `tests/sdk/query`.

Adding @eedeleon for confirmation.

For the `DPBenchmarkingFramework`, we should verify with @ankit-oss if the stochastic validator supports core at the moment, and ensure this works.

**Comment by ankit-oss** [comment]
Thanks Raman and Josh for fixing this. Yes, these test files and IPYNB were just for demo purposes that our interfaces can support smartnoise core aggregates to be passed for getting eval metrics vector that can then be visualized. So, fine to remove.

**Comment by joshua-oss** [comment]
Sounds good.  Note that we will have the new version of core library with a new programming model, releasing in alpha in a couple of weeks.  I will add back the core samples at that point.

**Comment by joshua-oss** [comment]
Fixed in #363

**Comment by ankit-oss** [comment]
Thanks Josh! Sounds great. I'll also make a few changes then in this notebook and try to move this interface one and work with Sha to demo RL method in samples repo.
