### ISSUE TITLE
Potentially infinite loop and privacy issue in MWEM implementation?

### ISSUE THREAD

**Issue by shlomihod** [opendp/smartnoise-sdk#439]
In the MWEM implementation, there is a while loop for making sure that no query is not chosen more than once (in the exponential mechanism part)

https://github.com/opendp/smartnoise-sdk/blob/3653e510d70f483e339219efa56e68e6ec5d5642/synth/snsynth/mwem.py#L245-L252

There are two issues with that:
1. It might lead to an infinite loop if the worst-performing query is chosen repeatedly, e.g., if the error is very high compared to the rest (this is how I actually discovered that after I run it on my data with eps=4).
2. I'm not sure if it is still DP with the same epsilon; or at least the original paper proof is without this step.

I checked two additional implementations for reference, and this step does not appear there:

1. Julia implementation by Moritz Hardt (co-author of the paper that presented the MWEM algorithm): https://github.com/mrtzh/PrivateMultiplicativeWeights.jl/blob/master/src/mwem.jl
2. Python implementation by Liu, Vietri and Wu (https://arxiv.org/pdf/2106.07153.pdf):  https://github.com/terranceliu/iterative-dp/blob/e5d7d28539fae0d2fed794168a78f97c869c0dbe/mwem.py#L39

I'd love to create a pull request if a change needs to be made.

**Comment by joshua-oss** [comment]
Thanks for flagging this issue.  Adding @lurosenb to discuss.

It does indeed look like an infinite loop is possible.  Line 249 is ensuring that we do not measure the same query more than once (i.e. it loops until it gets a query that has not already been measured).  This line of code is analogous to the reference implementation in Figure 8, the last page of the MWEM paper [1] starting with the comment `// determine a new query to measure, rejecting prior queries`.  The paper's reference implementation will also have an infinite loop if the number of possible queries is less than the number of iterations.  Line 234 of our code should be raising a warning when this is the case.

The infinite loop should only possible when the number of possible queries is less than the number of iterations.  Until all queries have been measured, there will be a non-zero (though perhaps small) chance that a remaining query will be selected.  So the selection loop will eventually terminate.  However, if all queries have been measured, the loop will never terminate.

Rather than using an unbounded loop to reject prior queries, the Julia implementation sets the differences of prior queries to 0.0, to make sure they don't get chosen in the argmax:
https://github.com/mrtzh/PrivateMultiplicativeWeights.jl/blob/master/src/mwem.jl#L34

In the Julia implementation, once all of the possible queries have been selected, they will all have the same probability of being selected.  Argmax always selects the first item, but the code adds Laplace noise, so it will uniformly randomly choose one of the queries that was previously selected, and re-measure it (line 73).

I am not sure we want to allow queries to be re-measured, but we can prevent the infinite loop.  I can think of a few options:

* Set some sort of `max_tries`, after which the algorithm finishes, since no suitable candidate queries are available.
* Calculate the number of possible queries, and automatically reduce the number of iterations to be the same.  Alternately, throw an error and offer guidance to the caller on choosing hyperparameters that will optimize budget usage
* After there are no more suitable candidate queries, remaining iterations silently stop measuring, and perform only the multiplicative weights update

Alternately, it _might_ be safe to re-measure queries, since the budget used for each measurement is divided over the number of iterations.  If we are convinced that this is safe, we could use one of methods above to determine that all candidate queries have been measured, and then switch to uniformly selecting candidate queries to measure.


[1] https://arxiv.org/pdf/1012.4763.pdf

**Comment by shlomihod** [comment]
@joshua-oss Thanks for the detailed response!

Just a quick note for now: I've encountered this issue when the number of queries was greater than the number of iterations, so apparently a previously measured query was still chosen by the exponential mechanism. I'm not sure how to quantify the probability of this event, perhaps my data was an outlier in this sense.

**Comment by joshua-oss** [comment]
> Just a quick note for now: I've encountered this issue when the number of queries was greater than the number of iterations, so apparently a previously measured query was still chosen by the exponential mechanism. I'm not sure how to quantify the probability of this event, perhaps my data was an outlier in this sense.

Thinking about this some more, I wonder if this could also happen if the cost of some of the unmeasured queries was coincidentally 0 (or extremely close to 0) at initialization time.  IOW, if the uniformly assigned weight in the synthetic histogram was the same as the actual count for that bin.  This would cause that query or queries to never get selected, or almost never selected.  We could mitigate this by randomly perturbing initial weights by a small amount, or with one of the mitigations mentioned earlier.

**Comment by lurosenb** [comment]
Hi y'all! Thanks for pointing this out Shlomi!

I think Joshua did a great job of listing potential avenues for mitigation. 

The "max_tries" change seems like the most straightforward initial patch, so I'll get that in now. 

But it is a very dissatisfying as a fix. Shlomi, do you have any interest in submitting a more comprehensive patch? Perhaps with the the automatic query count calculation+iteration adjustment and/or the adaptive epsilon spend that Joshua mentioned? Maybe other adjustments? Seeing as you were the first one to notice the issue we'd love your contribution! I'd be very happy to help you through this process.

Thanks!

**Comment by joshua-oss** [comment]
We've made some additional fixes and released as v0.2.7
