### ISSUE TITLE
Cannot find metadata when using `FROM database.schema.table`

### ISSUE THREAD

**Issue by oskarkocol** [opendp/smartnoise-sdk#456]
`FROM database.schema.table` will fail to find metadata for a dataset because `metadata.py` only matches statements with `schema.table`:
https://github.com/opendp/smartnoise-sdk/blob/186b81721c0f5c9ef9028e56a5ac142e9b362602/sql/snsql/metadata.py#L26-L29
**Possible solution**: to add an additional `if` statement that matches three elements from an identifier like `database.schema.table`

**Comment by joshua-oss** [comment]
I think the issue here is that the metadata specification assumes one database per metadata file.  The metadata file can have multiple top-level schemas in a single database, but does not allow multiple databases in the yaml file.  I don't think there is any reason we couldn't support multiple databases from the same connection, this was just an arbitrary design choice.

Assuming we want stick with one database per connection (probably simpler for now), we could still allow fully-qualified object names including database name, by providing some way for the caller or metadata to specify the database name.

One way to do this would be to augment the metadata to allow a top-level property for database name.  For example, `"database_name": "my_database"`.  This is somewhat awkward, since the other components of the name are part of the hierarchy of the YAML, but I think this is OK.

Another way to do this would be to allow the caller to pass in the database name to the connection's `NameCompare`, similar to how schema search path can be passed in now.  In this design, the database name (if present in the fully-qualified object name) would have to match the one passed in to the connection.  If no database name is passed in to the connection, we could choose to either throw an error, or silently accept it.

I'm leaning toward just adding a property to the root of metadata.  Thoughts?

We could also consider supporting multiple databases.  This would not be possible to do by extending the current metadata format, since schemas are currently at the top level.  We could take a breaking change to the metadata format to push database to top level.  The compatibility issues could be managed by introducing a version number to the metadata file format.  This is still a bit cumbersome, because it would end up requiring people to create an empty top-level for cases where the curator doesn't want to specify a database name, similar to how people sometimes currently use empty quotes as the schema name.  It might be worth it, though, and we could perhaps try to rationalize the metadata format to support more flexibly if people want to omit database name or schema name.  For example, we could use some heuristic whereby tables can exist at top level, and the metadata parser determines ancestor length by working up from the column definitions.

Another option would be to keep the exiting metadata convention of one database per file, and change to calling convention to allow people to pass in multiple metadata files.  This seems awkward, since the convention currently is to pass a file name, but maybe this could be handled by allowing file globbing.  For example, allowing a metadata file name like "myproject/*.yaml", which would make available all databases specified in the metadata files in the given project folder.

I'm leaning toward reworking metadata rather than changing calling convention, though I can see pros and cons either way.

Another consideration: it would be nice in the future to allow metadata to be stored in the database, where the data curator has full control.  To do this, we would probably use a table convention like (e.g.) `_schema_metadata` where each schema in the database would have metadata for all of the associated tables stored in the `_schema_metadata` table.  This would allow callers to pass in an established connection and query all of the tables without needing to pass in metadata.  In this scenario, however, the assumption is that the metadata for each database is stored only within that database.

And one other consideration: some engines allow linked servers, like `server.database.schema.table`.  This feels like an extreme edge case we can ignore, but just highlighting it here.

**Comment by joshua-oss** [comment]
I investigated some more, and this may be easier than I thought.  The metadata already has a top-level key for the database, it just gets thrown away when the metadata is being parsed.  We could add a property to the `Metadata` object which stashes the database name, and use that when resolving symbols.

Proposed behavior:

1. If 3-part name is used (`database.schema.table`), metadata must be available for all matching components.  If metadata available, query is rewritten and issued using the full 3-part name as provided in the original query.  It is up to the database engine to throw an error if the requested database name is not accessible.
2. If 2-part name is used (`schema.table`), metadata must be available for components matching the schema and table name.  The database name in the metadata will be ignored.  Rewritten query will be executed using the original 2-part name.  (This is the current behavior).  Should consider changing this behavior to only match a `schema.table` under a database that is set to empty string in YAML, or when the connection that has been passed in reports a database name that matches a database name in the metadata.
3. If 1-part name is used (`table`), metadata must be available for the table under the default schema, which is engine-specific (e.g. `dbo` or `public`).  For this, we could use empty string in the schema name in YAML to indicate the default schema.

**Comment by joshua-oss** [comment]
Fixed.
