### ISSUE TITLE
How do we vary split_factor in MWEM Synthesizer?

### ISSUE THREAD

**Issue by dsrishti** [opendp/smartnoise-sdk#488]
Hello Team,

We are facing few problems with MWEM synthesizer. It's working on some datasets and not working on others. We iterated and found that based on data size, we had to tune split_factor. Just wondering if we can automate deifining split_factor for any dataset of any size.

**Comment by joshua-oss** [comment]
Yes, the limiting factor for MWEM is that all counts need to be kept in-memory, and the memory/compute required explodes exponentially.  So the constraint is to partition the columns so that each set of columns will fit in a reasonable set of memory.  When choosing splits, you have to balance a few goals:

* Combine columns in such a way that the total dimensionality of each split fits within the memory resources available.  For example, if you have 10 columns, with 100 distinct categories in each column, that would be 100^10 cells if no splits are performed.  However, it would be only 50,000 cells total if split into 5 splits.  Splits with 3 columns would easily fit in memory with this setup, and possibly 4 columns.
* Minimize the number of splits, because epsilon is divided across splits.
* Keep columns that are associated with each other in the same splits.  This is because each separate split will be treated as independent.

The first two goals are not too hard to automate, since you just count the number of categorical values in each column and select permutations of the columns that fit.  It's the third goal that makes things tricky.  If you have some domain experts who can partition the columns in a way that the separate splits are unlikely to be associated, you can use those splits without incurring privacy cost.  In absence of domain expertise, you can spend some epsilon to try to discover which columns are the most independent.  One very crude way to do this:

1.  Compute differentially private counts of all dimension combinations, perhaps using `smartnoise-sql` with a large GROUP BY query.  So, for example, you have `SELECT sex, age, educ, race, COUNT(*) FROM PUMS.PUMS GROUP BY sex, age, educ, race`.
2.  Postprocess the noisy counts to estimate mutual information for all 2-column pairs.  For example, (educ, race), (sex, race), (sex, age), and so on.  Rank the column pairs by mutual information, and ensure that pairs with the highest mutual information stay in the same splits.  For larger numbers of columns, you can rank to decide with 3-way marginals should be together and so on.

This approach leaves a lot to be desired, though:

* The two-way (and 3-way) marginals are being marginalized from noisy counts over k-way marginals, where k is potentially large.  The larger the number of cells being marginalized over, the more the noise impacts the aggregate count, which impacts the accuracy of the MI ranking.  Depending on the data, you could end up wasting epsilon to get splits that aren't much better than random.
* Real data is unlikely to have independencies conveniently located between evenly-sized clumps of dimensionality.  Some splits are better than others, but all splits are likely to lose information.
* Computing the joint frequency and discovering dependencies is exactly what the synthesizer is trying to do anyway.  Conceptually, if you did a big GROUP BY query with no noise, you could sample from the counted frequencies to generate synthetic data.  So the process of using these (noisy) counts to try to determine splits is spending epsilon to discover a joint distribution in a manner that's virtually always going to be less efficient than MWEM's algorithm.  Of course, you could use the counts from this split procedure in concert with the learned MWEM cubes to get slightly better synthetic data, but the epsilon spent on the splits would still be the least efficient epsilon spent.

Another way to think of it, if you hypothetically had a Bayesian causal graph describing your data, you could use an automated procedure to determine the best possible splits by looking for independent portions of the graph.  You could discover a causal graph by using some off-the-shelf graph discovery algorithms.  But, if you already had that graph, you would have a synthesizer, and if the graph were discovered in a way that wasn't differentially private, it wouldn't be safe to use it for synthesis or splits.

Note that the MST algorithm actually uses some budget to discover the most associated marginals, and then focuses the privacy budget on the marginals that are most likely to contain information.  However, this basic graph discovery is used to optimize accuracy rather than to partition the synthesizer into disjoint cubes.

**Comment by dsrishti** [comment]
Thanks @joshua-oss for the detailed answer. Our team will work to automate this based on the suggestions you have mentioned!
