### ISSUE TITLE
Loading multiple separate dataframes with the same metadata

### ISSUE THREAD

**Issue by FishmanL** [opendp/smartnoise-sdk#503]
The metadata provides support for having multiple tables in one schema -- how do I connect multiple dataframes to metadata with multiple tables?

**Comment by FishmanL** [comment]
is it not possible?

**Comment by joshua-oss** [comment]
The multi-table scenario is meant for database engines where a database holds a collection of tables.  In the case of pandas dataframes, the "connection" we get to the factory to create the `PandasReader` is a single table.  Since we don't pass in any table name information, the PandasReader just grabs the first table in the metadata.

We could fix this by allowing people to pass in a dictionary of pandas dataframes keyed by a desired table name.  For example:

```python
from snsql import from_connection, Privacy
import pandas as pd

classes = pd.read_csv('classes.csv)
students = pd.read_csv('students.csv')
meta = '../education.yaml'

reader = from_connection({'students': students, 'classes', classes}, meta=meta, privacy=Privacy(epsilon=1.0))
```

Another option would be to finally implement the SQLiteReader and provide a utility to populate a new SQLite database from a collection of pandas dataframes.  That would give better performance for people doing lots of queries, but would add an extra step for people who want to just quickly query a couple of pandas dataframes.

**Comment by FishmanL** [comment]
Ah, yep, I see.

**Comment by joshua-oss** [comment]
This has been added to smartnoise-sql==1.0.0.  Multiple pandas datafranes can be passed in with a dictionary.
