### ISSUE TITLE
Add anonymization transformer

### ISSUE THREAD

**Issue by neat-web** [opendp/smartnoise-sdk#505]
### User story
As a user of the `smartnoise-synth` library, I frequently want to anonymize personally identifiable information (PII) in the data.

### Detailed description
To prevent leakage of sensitive information PII is anonymized by an analyst when preprocessing the data. Generating fake data is a solution because it discards existing values and instead uses entirely new ones. The most popular library for this is [Faker](https://pypi.org/project/Faker).

### Proposed solution
One possibility would be to follow the idea of the Synthetic Data Vault (SDV) [implementation](https://github.com/sdv-dev/SDV/discussions/667). It integrates `Faker` and allows a user to pass an `anonymize_fields` keyword argument. This maps a column to a corresponding provider. Even though that is quite user-friendly, it restricts the usage of more complex generation ideas, e.g. providing a custom implementation.

Therefore, I suggest not to integrate `Faker` directly, but instead let the user pass a function for generating fake data. Since data transforms can be provided in a `TableTransformer` object, I suggest implementing a new `ColumnTransformer` class for anonymization.

Feel free to make suggestions. I will implement the functionality soon.

**Comment by joshua-oss** [comment]
That's a great idea.  I think it's OK to take a dependency on faker for their built-ins, but I also like the idea of allowing overrides.  As you suggest, this should be possible by deriving `snsynth.transform.base.ColumnTransformer` .  Since it will be assuming the column is PII, it shouldn't be necessary to implement anything for `_fit`, just for `_transform` and `_inverse_transform`.  Presumably the `_transform` just scrubs the value, and `_inverse_transform` generates fake PII when reversing the transform.

The current `ColumnTransformer` design allows `_transform` to map from 1 to n columns, with `_inverse_transform` mapping back from n to 1.  I'm not entirely sure the best way to handle this with, for example, a single column of PII.  Conceptually, the whole PII column is dropped, but then we have nothing to invert back (we can't map 1-->0 and then 0<--1).  An easy choice would be for `_transform` on the anonymizing `ColumnTransformer` to emit a column of `None` that the `TableTransformer` can then ignore when feeding the synthesizers (and re-inject on reverse transform).  So, the anonymizing column transformer would only emit the column of `None` when operating standalone or in a `ChainTransformer`.

Of course, I am assuming that the synthesizers don't want to train on fake PII, so it's best to drop those inbound and add the fakes outbound.  However, there might be cases where someone wants to replace real PII with fakes in both directions, in which case `_transform` could add fakes.

I'm assuming some of the more common types of PII could be specified when creating the column transformer:

```python
anon = TheNewColumnTransformer(some_prop_to_specify_fake_type='email')
assert(anon.fit_complete)
scrubbed = anon.transform(my_email_list)
reversed_emails = anon.inverse_transform(scrubbed)
assert(len(reversed_emails) == len(my_email_list))
```

And then maybe that could also take a caller-provided function per your proposal?

If you get the `ColumnTransformer` implemented, I can plug it in to `TableTransformer` and the data type inference stuff.  This would actually unblock a feature we want to add for SQL as well, so we can auto-generate metadata.

**Comment by neat-web** [comment]
Thanks for your feedback. I agree on the proposed functionality / API and will start implementing the `ColumnTransformer` subclass.

**Comment by neat-web** [comment]
Thanks @joshua-oss for implementing the tests and basic PII inference in #515.

I think it is important for a user to be able to read the documented API / examples. Can you rebuild the synthesizers / transforms documentation with the latest additions?

**Comment by joshua-oss** [comment]
Yep, I attempted to do it when pushing, but there is some syntax error that is making Sphinx crash.  I'll fix that shortly and push a doc update.

**Comment by joshua-oss** [comment]
Done!  There were just two underlines that were too short, and then a breaking change in pydata-sphinx-theme.
