### ISSUE TITLE
Constrain inferred preprocessor

### ISSUE THREAD

**Issue by neat-web** [opendp/smartnoise-sdk#517]
### User story
As a user of the `smartnoise-synth` library, I want to provide a variable amount of `ColumnTransformer` objects for preprocessing during `fit()`. Especially if the data contains many columns or the majority of the inferred transformers is OK, this can save time and repeated definitions.

### Detailed description
Currently, one either specifies the whole preprocessor (i.e. at least one transformer per column) or allows the synthesizer to infer the preprocessor completely. By specifying only certain `ColumnTransformer` objects, a user can constrain the inferred preprocessor to certain columns.

For my use case I would like to enforce that e.g. the "age" column uses an `AnonymizationTransformer` even when I am content with the other inferred transformers.

### Proposed solution
In my opinion, one could specify an optional parameter `fit(transformer_constraints=...)` which takes a dictionary that maps from column indices / names to a `ColumnTransformer` object. Assuming `transformer=None` is given, then all except the referenced columns will be inferred.

Another approach is to modify the `TableTransformer` class directly. Instead of assuming that the parameter `transformers` is solely a list, it could be similar to the described dictionary. If some columns are missing in the given `TableTransformer` object, they can be inferred automatically.

I will open a new branch and work on this once we agree on the specifics.

**Comment by joshua-oss** [comment]
Good idea.  

Regarding the two proposals, the `SDGymBaseSynthesizer.fit()` method currently takes three lists (`ordinal_columns`, `categorical_columns`, and `continuous_columns`), which are passed through to the `TableTransformer` factory methods.  The idea is that creating a `TableTransformer` manually and passing to the synthesizer, or allowing the synthesizer to create a `TableTransformer` under the covers, will result in the same behavior.  Ideally, whatever is designed for the above proposal should have the same symmetry.

The current design was a holdover from our SDGym heritage, where there were only 2 or 3 column types allowed, and any column not specified in one of two types would be assumed to be the third type.  That was problematic in our setting, so we switched to requiring all columns to be explicitly listed, and we throw an error (rather than assuming) if a column is present in the training data but has an unknown type.  The inference code mitigates this somewhat, but the point is that the code requires all columns present to have a transformer, and only allows transformers to be generated from 3 types (ordinal, categorical, and continuous).

With the recent PR to support anonymization, I added a `special_types={}` dictionary to all factory methods, and the inference code uses RegExes to try to guess if any columns need to be "special".  In this code path, "special" can include datetime as well as anything with a built-in faker.  I didn't add this param to the `fit` method of the base synthesizer, because I wasn't convinced it was the right general-purpose design.  But it or something like it could be passed through from the `fit` method to maintain the symmetry of the `fit` and `TableTransformer`.  For the proposal above, maybe we could rename `special_types` to something more suitable and use it as specified above.

This is awkward, since the dictionary needs to cohere with the three lists that are passed in as legacy from SDGym.  For example, supporting `datetime` could have been accomplished by adding a new list, `datetime_columns` to match the `categorical_columns` and so on, but this gets unwieldy quickly.  But adding a dictionary where the column is mapped to `datetime` raises the question of why we even have `continuous_columns` etc. at all.  If we were designing from scratch, we would just use the dictionary and not include the three lists.  I'm open to moving everything to dictionary and finding a way to cleanly deprecate those lists (or maintain purely for back compatibility).  If supporting an optional dictionary as the primary way to manually specify column types, I would imagine specification something like:

* any column not specified in dictionary will be inferred
* to ignore a column completely, caller can specify in dictionary with "drop" or "ignore"
* any column specified in dictionary will be ignored for purposes of inference and will not incur privacy cost to create transformer.  
* dictionary entry should support most built-in transformer types, including fakers, and include text shortcuts as well as manually instantiated transformers

In this pattern, we could even allow the "transformer" property on the "fit" method to take a dictionary, so there wouldn't need to be a new param.  For example:

```python
synth = Synthesizer.create("mwem", epsilon=2.0)
synth.fit(data, transformer={'address': 'address'})  # all columns except address are inferred; age is faked using 'address' built-in
```

```python
synth.fit(data, transformer={'device_id': AnonymizationTransformer(my_faker_func)}) # all inferred except customized ID column
```

```python
synth.fit(data, transformer={
   'age': 'ordinal',
   'notes': 'ignore',
   }). # all other columns inferred
```

**Comment by neat-web** [comment]
The implementation was reviewed and merged.

I would be grateful if you could push a new release @joshua-oss. Also, it would be a good idea to remove the `special_types` dictionary, include a simple end-to-end test and document a usage example.

**Comment by joshua-oss** [comment]
I've added some documentation and end-to-end tests and pushed a release to PyPi.  I wasn't able to cleanly remove `special_types`, so that code remains as undocumented implementation detail for now. Removing it was breaking the code that runs regular expressions on the unbounded string columns to guess the right faker to use.  It is safe to always pass an empty dictionary, which is the default.

The RegEx inference was written with the assumption that the SDGym style of passing "categorical", etc. was mutually exclusive with inference (because RegEx of PII only makes sense on unbounded strings/ints, which isn't one of the 3 options SDGym had).  Now that you've updated to allow column-based control over what gets inferred, the RegEx code should be updated to invoke on anything not defined in constraints.  However, using constraints currently mixes fine with the RegEx code, except for cases where constraints use the SDGym-style string shortcuts.  In that case, the inference may be suboptimal, but won't introduce any privacy bugs, so I'll leave it as-is for now.

**Comment by neat-web** [comment]
Great! Okay then let's stick with `special_types` for now.
