### ISSUE TITLE
Use of delta parameter in Privacy 

### ISSUE THREAD

**Issue by sanattaori** [opendp/smartnoise-sdk#537]
Hi Team,
I want to know what is actual use of delta parameter, changing delta with constant epsilon does not affect the results, can someone please explain in detail.

**Comment by joshua-oss** [comment]
Hello @sanattaori, the `delta` will be used if the gaussian mechanism is used, or if Laplace is used to censor dimensions.  The delta term bounds the probability that the mechanism will fail to provide the desired epsilon.  Normally delta should be set to something small, like `1/(n * sort(n))`.  If your workload only uses geometric or Laplace mechanisms, and you are not censoring dimensions, the delta will not be spent.  If you are using gaussian mechanism, you can sometimes get better budget usage over multiple queries by supplying an epsilon.  To see how the budget is actually spent, you should always check the odometer, as described here:

https://docs.smartnoise.org/sql/advanced.html#managing-privacy-budget

It's a good idea to always use the odometer, because SmartNoise will try to optimize which mechanisms get used to give best results, so it won't always be obvious how much the total workload will cost.  The documentation linked above also discusses how to check the total spend of a batch of queries, and how to override mechanisms if you want tighter control over what SmartNoise does.

**Comment by sanattaori** [comment]
Thank you, this is very much helpful.

**Comment by sanattaori** [comment]
Thank you @joshua-oss
