### ISSUE TITLE
Aggregate over expression

### ISSUE THREAD

**Issue by myyong** [opendp/smartnoise-sdk#546]
I am trying find the average length of time between two DateTimes. My SQL query is along the lines of:

```sql
SELECT avg(col_date_a - col_date_b) FROM table_x
```

As documented in your README, I am getting the ` We don't support aggregation over expressions` message. Do you have any suggestions for this particular query?

Thank you!

**Comment by joshua-oss** [comment]
The best way to handle this is to preprocess the table to have a duration column, and then specify the min and max values for that duration column in your metadata.

The reason for this is that we can't guess the sensitivity for an expression like this, because the difference between two dates could be effectively unbounded, and the amount of noise needed to protect (e.g.) a ten year duration could be unreasonably high.  So we normally handle this by specifying a duration min and max.  It often makes sense to set max at a level that is smaller than outliers.

This is also the general reason we don't support outer expressions, since it's often impossible to infer the sensitivity.  We could do so in simple cases like SUM(foo * 10), but those are easy enough to rewrite as inner expressions like SUM(foo) * 10.  It's just particularly impractical with dates and times.
