### ISSUE TITLE
NaN STDDEV

### ISSUE THREAD

**Issue by mhauru** [opendp/smartnoise-sdk#547]
I'm trying to do a query that computes the`STDDEV` of a float column. I'm getting intermittent `RuntimeWarning: invalid value encountered in sqrt` and a resulting standard deviation that is NaN. I think this is because the SQL query is used to compute the expectation of X^2 and of X, noise is added to both, and then the stddev is computed as `sqrt(E[X^2] - E[X]^2)` in python-land. Sometimes the noise takes E[X^2] to be very small or negative, and the expression within the square root is negative.

**Comment by joshua-oss** [comment]
Yes, we throw an error on divide by zero and invalid square root, since this is the behavior Postgres uses.  That is, if you hand-computed the formula on the underlying values, it would also throw an exception in Postgres.  I suppose it's somewhat counterintuitive, since Postgres  doesn't add noise to counts or sums, so it never happens when using STDDEV or AVG on Postgres.  It can only happen in an expression that implements the formula and has noisy inputs. 

We could easily switch to returning NaN with no error, or we could add a switch to return NaN on math errors.  Given the noisy nature of our values, maybe the best option is to default to NaN with no exceptions raised, and offer an override if people want to throw exceptions on math errors?

**Comment by joshua-oss** [comment]
I just double checked and realized we made that change already; so it returns NaN if it's not possible to compute the value from the noisy values.  There isn't really a way to recover from that, so we either have to return NaN or throw.  We can add an option to throw if that's desired.

For AVG, the semantics of SQL is that count of 0 will always return 0 AVG, since it's not possible to have a SUM of > 0 over 0 rows.  We could also throw NaN here, but it's possible in this case to be more consistent with expectations for SQL, so we keep the AVG 0.  It can also be missing rather than 0 if censor_dims = True.

**Comment by mhauru** [comment]
Would it be possible to add the noise only after the sums are combined to compute the standard deviation? That would coincide more with the intuitive notion that the result you get is the standard deviation, but with noise added.

My problem isn't so much with what exactly is returned, and if the result is a NaN I think a warning is fair, and I wouldn't want it to result in an error throw. (It would be strange if simply computing the standard deviation of entirely acceptable data would result in an error, and intermittently too.) Rather my problem is that from a user point of view, asking for the standard deviation of a variable but with noise added to protect privacy sounds like an entirely reasonable request, and the fact that the result is sometimes a NaN is quite confusing and unexpected.

It's especially confusing because the operation would be fine if either a) noise was added to the original data, and then stddev was computed, or b) the stddev was computed, and noise was added to that. It's only because the addition of noise is done at an intermediate stage that problems arise. This is hard to understand for someone who isn't deeply familiar with how SNSQL works.

**Comment by joshua-oss** [comment]
The reason we do not add noise after the subtraction is that the sensitivity computation relies on the exact `n`:

`((upper - lower) / n) **2. * (n - 1)`

Using the exact `n` would leak privacy, so it is only safe to use this approach when `n` is considered public.  On the other hand, if we use a noisy `n`, it could leak privacy by returning sensitivity that is too small.  Using the sensitivity with the exact `n` gives much better accuracy.

You make a good case, however, that NaN is not a good return value in situations where the noisy E[X^2] is smaller than the noisy E[X]^2.  NaN here indicates "this answer is probably nonsense", but we do have more information that we can safely return to the user. 

This will happen more frequently when variance is small and/or when epsilon is very small relative to sample size.  So we should find a way to communicate that.  I can think of a few ways to handle it better:

1. Always return zero if the subtracted value is <= 0.  This is debatably OK, since zero is definitely in the interval of possible values, and we are essentially clamping the noisy value to the closest valid value.  However, returning zero might make someone think their data are very low variance when in fact maybe the epsilon is tiny and variance is relatively high.

2. Take the absolute value of the subtraction. That way the results would still show variance.  But may be even more misleading, since the absolute value of a negative variance is statistically less likely that zero to be the true variance.

2b. Return the actual negative value.  Then people who have multiple queries over same variance could sum them and get an answer closer to the truth.  STDDEV still needs a different workaround.

3. Use noisy `n` with some crude heuristics to try to make it safe. Using a smaller `n` will not create a privacy bug, if we know the smaller `n` is measured in a private way.  For example, take a noisy count and the multiply by 0.9, then use that in the sensitivity calc.  The main issue is that we would need to be able to prove that our "smaller n" could *never* end up being bigger than n.  That becomes difficult or impossible when `n` is small or when epsilon is very tiny.

4. Allow curator to set exact `n` in metadata, such that we can treat it as public.  Then we would need to reservoir sample the whole table on every query to make sure we never exceed `n` rows.  This is not a bad idea for (e.g.) social sciences scenarios.

5. Sample and zip a list of around 1,000 values for each row of aggregates (similar to what we will need to do for min and max), then use the better sensitivity to compute locally.  This would require that we select a sample size smaller than the number of rows, so would only make sense on relatively larger data.

**Comment by mhauru** [comment]
Of the options you listed, 1. seems preferable to 2. to me, 3. seems hard to implement, 4. sounds like it would only cover some use cases, and 5. sounds interesting but I lack the background to understand it properly.

Could we get around the issue where the sensitivity computation relies on exact `n` by considering the same formula but thinking of `n` as the outcome of `COUNT(*)` query, for which sensitivity is 1, and applying the rules of how sensitivities combine? So if we want to compute the sensitivity of `SUM(X^2)/N - SUM(X)^2/N^2`, then think of that has computing the sensitivity of `SUM(X^2)/COUNT(X) - SUM(X)^2/COUNT(X)^2`, where if sensitivity of `SUM(X)` is `S`, then the sensitivity of `SUM(X^2)` is `S^2` and sensitivity of `COUNT(X)` is 1, and thus if I've got the rules of sensitivity-algebra correct the total sensitivity would be `S^2/1 + S^2/1^2 = 2 S^2`. This may be misguided since I'm not an expert on this stuff, please do set me right if that is the case.

**Comment by joshua-oss** [comment]
You are correct that (upper - lower)^2 is an upper bound on sensitivity.  The challenge is that this is so large as to overwhelm the actual value and leave no information.  Consider the case of n = 2.  In that case, the sensitivity formula yields (1/4)(upper - lower)^2.  So a smaller sensitivity, but still 250X what you'd get if you had 1,000 records.  Essentially, this is fixing the noise as in randomized response/local differential privacy, such that accuracy can't increase as sample size increases.

On the other hand, this is somewhat similar to approach 3 above, except that it fixes the 'n' to be 1 rather than trying to find a "safe" bigger 'n'. I am wondering if we could take advantage of a delta term and the noise scale on the count to estimate the "smaller n" in such a way that we guarantee with probability (1 - delta) that the n won't exceed the exact n.

I will update the code to return zero when the interval goes negative, and I'll also investigate ways to get better sensitivity there.

**Comment by mhauru** [comment]
I'm not sure I understand the issue with (upper-lower)^2. This would be the sensitivity for the variable that is E[X^2] - E[X]^2, right? That scale is indeed overwhelmingly large compared to X, but it's of the same magnitude as values of X^2, which is what the noise would be added to if I've understood this correctly. In the case of computing `STDDEV` it would also then be scaled back down by taking the square root.

It seems though that you have a plan, so I'll just look forward to the new version. Thanks for being so responsive with the flood of issues I've opened. :)

**Comment by joshua-oss** [comment]
I was a bit sloppy in using SUM(X^2) interchangeably with E[X^2].  It's the SUM that gets the gigantic sensitivity, and we add that noise to large SUM and then divide by the noisy 'n' (which has much smaller noise).  So the variance gets more accurate with higher 'n', whereas if used that sensitivity after computing the E[X^2] - E[X]^2 we lose the ability to divide the noise by 'n'.  I'm also just talking about variance, since STDDEV is just post-processing of variance, so any fix to variance accrues to STDDEV.

Because we get to use the noisy n, our accuracy guarantee can be much better than the (upper - lower)^2 bound, but substantially worse than if we used exact 'n'.  Our accuracy bounds for VAR is documented in [1] at formula (9).  I just ran some tests, and our formula does a good deal better than the X^2 upper bound as n > 5, but always does worse than exact 'n' in any reasonable scenario I could contrive.  So I would really like to find a way to use a safely private "smaller n" at some point in the future.

[1] https://github.com/opendp/smartnoise-sdk/blob/main/sql/docs/papers/DP_SQL_budget.pdf

**Comment by mhauru** [comment]
Thanks, this makes sense now.

**Comment by joshua-oss** [comment]
VAR and STDDEV now return 0.0 when the variance computation goes negative, related to PyPi smartnoise-sql==0.2.12

**Comment by joshua-oss** [comment]
> You are correct that (upper - lower)^2 is an upper bound on sensitivity. The challenge is that this is so large as to overwhelm the actual value and leave no information. Consider the case of n = 2. In that case, the sensitivity formula yields (1/4)(upper - lower)^2. So a smaller sensitivity, but still 250X what you'd get if you had 1,000 records. Essentially, this is fixing the noise as in randomized response/local differential privacy, such that accuracy can't increase as sample size increases.
> 
> On the other hand, this is somewhat similar to approach 3 above, except that it fixes the 'n' to be 1 rather than trying to find a "safe" bigger 'n'. I am wondering if we could take advantage of a delta term and the noise scale on the count to estimate the "smaller n" in such a way that we guarantee with probability (1 - delta) that the n won't exceed the exact n.
> 
> I will update the code to return zero when the interval goes negative, and I'll also investigate ways to get better sensitivity there.

Following up on this, we did some analysis of taking advantage of the `delta` term and found that this approach does not perform as well as our current algorithm.
